### ISSUE TITLE
Handle user not found situation.

### ISSUE THREAD

**Issue by ducthienbui97** [ducthienbui97/pullrequests#18]
Currently, if there is some problem with request, we will ask user to open console log. However with common cases like user not found, we should alert user about that.

https://github.com/ducthienbui97/pullrequests/blob/65f5e3a8e2cbc357c3ec99d8d49ce95164cfcad8/src/components/User.js#L20
![3vi1wwzc4m](https://user-images.githubusercontent.com/10867758/31111060-0ecc2012-a857-11e7-8c87-b96dc967cb7e.gif)

**Comment by wildan3105** [comment]
Hi, I'd like to work on this. Do you give me a shot?

**Comment by ducthienbui97** [comment]
@wildan3105 Check the [contributing file](https://github.com/ducthienbui97/pullrequests/blob/master/CONTRIBUTING.md) for more information of contribute process. Feel free to open a PR about this issue as long as this issue is opened even if someone opened a PR before you.

**Comment by wildan3105** [comment]
Thanks. Will do that accordingly

**Comment by martskins** [comment]
Just submitted a PR for this. It displays the error message if it's available. I believe it's clear enough.
