### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by ducthienbui97** [ducthienbui97/pullrequests#5]
Currently Codacy grade is only C. Should refactor to get A.

**Comment by the-cybersapien** [comment]
Can I work on this?
I think I can improve this over 2-3 PR, tackling different issues

**Comment by ducthienbui97** [comment]
@the-cybersapien   Check the [contributing file](https://github.com/ducthienbui97/pullrequests/blob/master/CONTRIBUTING.md) for more information of contribute process. Feel free to open a PR about this issue as long as this issue is opened even if someone opened a PR before you.

**Comment by ufocoder** [comment]
I've send PR, then we (I or @the-cybersapien ) could improve and refactor each file after you (@ducthienbui97) will accept this PR

**Comment by the-cybersapien** [comment]
Already fixed the issues with the `registerServiceWorker.js`. Waiting for @ufocoder 's PR to be accepted/denied before making mine, since structure change will cause conflicts.

**Comment by ufocoder** [comment]
@ducthienbui97 @the-cybersapien By the way I suggest we can also refactor the followings:
* Rewrite `App`, `Load` components as functional components #8 
* Extract styles from `PullRequest` component #9 
* Extract `GithubService` that will be able to fetch data from Github #10

**Comment by nghduc97** [comment]
Oh didn't notice you modifying the stucture, I refactored the files, it's all A except the registerServiceWorker.js now.

**Comment by ducthienbui97** [comment]
@ufocoder  feel free to open new issues for your suggestions 👍

**Comment by ducthienbui97** [comment]
@lazyc97  can you update your PR to resolve conflict with current master branch?

**Comment by ufocoder** [comment]
@ducthienbui97 I've created issues
@the-cybersapien PR is accepted, now you can continue with SW, thanks for waiting

**Comment by the-cybersapien** [comment]
@ducthienbui97 completed with #11 , `registerServiceWorker.js`
This alone gave a Codacy Score of B. Working on the remaining files now.

**Comment by ducthienbui97** [comment]
@the-cybersapien Wait, @lazyc97  has already been doing with other files.

**Comment by nghduc97** [comment]
@ducthienbui97 No he is only dealing with `registerServiceWorker.js`

This file came along with `create-react-app` so I think it should be excluded from codacy instead of modifying it 🤔

**Comment by the-cybersapien** [comment]
@lazyc97 Nope. There's some custom code in there, and that is where most of the errors branched out from.
I ran a Codacy check myself, I have a feeling this will improve the score without needing to exclude it.

**Comment by ducthienbui97** [comment]
I think this issue can be closed now. Feel free to send PRs for the issues created by @ufocoder
