### ISSUE TITLE
Rewrite components as functional components

### ISSUE THREAD

**Issue by ufocoder** [ducthienbui97/pullrequests#8]
Rewrite as functional components:
* `src/components/App` component
* `src/components/Load ` component

**Comment by JesseSingleton** [comment]
I can have a crack at this. Will give it a go and open a PR! 👍

**Comment by ducthienbui97** [comment]
@JesseSingleton   Check the [contributing file](https://github.com/ducthienbui97/pullrequests/blob/master/CONTRIBUTING.md) for more information of contribute process. Feel free to open a PR about this issue as long as this issue is opened even if someone opened a PR before you.
