### ISSUE TITLE
Extract styles from `PullRequest` component

### ISSUE THREAD

**Issue by ufocoder** [ducthienbui97/pullrequests#9]
Refactor and extract styles from `src/components/PullRequest` component into CSS file.
As variant `PullRequest` component can be could and its possible structure could be the following:

```
- src
  ..
  - src/components/PullRequest
    - src/components/PullRequest/styles.css
    - src/components/PullRequest/index.js
```

**Comment by JipSterk** [comment]
i would like to refactor this in to separate files
do you want this to be in styles.css or do you want it a pullRequest.css file
